### PR TITLE
fix: allow `tomli-w` versions above `v1.0.0`

### PR DESCRIPTION
**Pull request by turboBasic**
### 🤔 What's changed?

- Allow `tomli-w` above `v1.0.0`
- Allow `tomli` from `v2.0.1` up to `v3`
- Allow `natsort` from `v.8.4.0` up to `v9`

### ⚡️ What's your motivation? 

Fixes following error:

```
An unexpected error has occurred: CalledProcessError: command: ('$HOME/.cache/pre-commit/repo6a1zzrzt/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
...
stderr:
    ERROR: Some build dependencies for file:///$HOME/.cache/pre-commit/repo6a1zzrzt conflict with the backend dependencies: tomli-w==1.1.0 is incompatible with tomli-w==1.0.0.
```

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by louisbzk** [comment]
Hi, I had the same problem with the `tomli-w` dependency. I solved it using `tomli-w>=1.0.0` and skipping the `pyprojectsort` pre-commit hook. Not sure how it can be done in a clean way though.

**Comment by turboBasic** [comment]
It looks like it fixes #77

**Review by kieran-ryan — CHANGES_REQUESTED** [review]
@turboBasic, thanks so much for the contribution! Missed notification. Would it be possible to provide me with access to contribute on your fork? Wanted to cherry-pick in change from @louisbzk into your branch - to ensure their contribution is included - though being from the `main` branch on the fork prevents.

Though otherwise you may be able to apply same.

```console
git remote add fork https://github.com/louisbzk/pyprojectsort
git fetch fork
git cherry-pick fork/main
```

Then accept and push the incoming changes.

```console
git cherry-pick --continue
```

**Comment by turboBasic** [comment]
hi @kieran-ryan, I will do it shortly

**Comment by kieran-ryan** [comment]
Appreciate it @turboBasic - will take a look - thanks a mill!

**Review by kieran-ryan — APPROVED** [review]
Awesome!

- Switched CHANGELOG entry from `Added` to `Fixed`
- Changed GitHub workflow Python 3.13 image from `3.13.0-beta.3` as 3.13 is officially released
- Retained pyprojectsort in pre-commit - allowing to fail for now - and will update dependency version on project release

**Comment by kieran-ryan** [comment]
Released @turboBasic and @louisbzk 🚀 Thanks a mill for the contributions - feel free to try and report whether any issues

https://github.com/kieran-ryan/pyprojectsort/releases/tag/v0.4.0

**Pull request merged**
